name: GitHub Pages

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4

      - name: Install pnpm
        working-directory: webui
        run: corepack enable

      - name: Install dependencies
        working-directory: webui
        run: pnpm install

      - name: Build
        working-directory: webui
        run: pnpm build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: webui/dist

  deploy:
    needs: build

    if: github.ref_name	== 'main'

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
